# Generated by Django 4.1.7 on 2023-04-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apiapp', '0003_user_delete_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
