# Generated by Django 4.1.7 on 2023-04-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apiapp', '0007_person_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
